
# ----------
# view
# ----------
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'lsdr/monokai'
hook_add = '''
  if !exists('g:vscode')
    au VimEnter * nested colorscheme monokai
  endif
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'

# -------
# coding
# -------
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_enabled = 1
  let g:indentLine_concealcursor = 0
  let g:indentLine_faster = 1
  let g:indentLine_color_term = 1
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
  nnoremap <F7> :FixWhitespace<CR>
'''

[[plugins]]
repo = 'preservim/nerdcommenter'
hook_add = '''
  let g:NERDSpaceDelims = 1
'''

# ------
# motion
# ------
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'asvetliakov/vim-easymotion'
hook_add = '''
  map <Leader><Leader>s <Plug>(easymotion-bd-f2)
  map <Leader><Leader>l <Plug>(easymotion-lineforward)
  map <Leader><Leader>h <Plug>(easymotion-linebackward)
'''

# ------
# icons
# ------
[[plugins]]
repo = 'ryanoasis/vim-devicons'
