
# ----------
# view
# ----------
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  au VimEnter * nested colorscheme tender
'''


# ----
# git
# ----
[[plugins]]
repo = 'tpope/vim-fugitive'


# -------
# coding
# -------
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_enabled = 1
  let g:indentLine_concealcursor = 0
  let g:indentLine_faster = 1
  let g:indentLine_color_term = 1
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
  nnoremap <F7> :FixWhitespace<CR>
'''

[[plugins]]
repo = 'preservim/nerdcommenter'


# ------
# shell
# ------
[[plugins]]
repo = 'thinca/vim-quickrun'

