
# ---------
# Markdown
# ---------
[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'

[[plugins]]
repo = 'previm/previm'
on_ft = 'markdown'
hook_source = '''
  let g:previm_disable_default_css = 1
  let g:previm_custom_css_path = 'C:/Users/10035637417/vimfiles/stylesheet/markdown.css'
  nnoremap <F5> :PrevimOpen<CR>
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_source = '''
  let g:vim_markdown_conceal=0
'''

# ---------
# PlantUML
# ---------
[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'markdown'

# -----------
# powershell
# -----------
[[plugins]]
repo = 'PProvost/vim-ps1'
on_ft = 'ps1'

# -----------
# toml
# -----------
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

