
# ----------
# view
# ----------
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  au VimEnter * nested colorscheme tender
'''


# ----
# git
# ----
[[plugins]]
repo = 'tpope/vim-fugitive'


# -------
# coding
# -------
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_enabled = 1
  let g:indentLine_concealcursor = 0
  let g:indentLine_faster = 1
  let g:indentLine_color_term = 1
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
  nnoremap <F7> :FixWhitespace<CR>
'''

[[plugins]]
repo = 'preservim/nerdcommenter'
hook_add = '''
  let g:NERDSpaceDelims = 1
'''


# ------
# shell
# ------
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = {
  \  "_": {
  \    "runner": "vimproc",
  \    "runner/vimproc/updatetime": 100,
  \    "hook/output_encode/enable": 1,
  \    "hook/output_encode/encoding": "cp932",
  \    'outputter' : 'error',
  \    'outputter/error/success' : 'buffer',
  \    'outputter/error/error'   : 'quickfix',
  \    "outputter/buffer/close_on_empty": 1,
  \  },
  \  "go": {
  \    "exec": "go run %s:p:t %a",
  \    "hook/time/enable": 1
  \  }
  \}
'''

