
# ----------------------
# brackets completement
# ----------------------
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# ----
# coc
# ----
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_add = '''
  let g:airline#extensions#coc#enabled = 0
  let airline#extensions#coc#error_symbol = 'Error:'
  let airline#extensions#coc#warning_symbol = 'Warning:'
  let airline#extensions#coc#stl_format_err = '%E{[%e(#%fe)]}'
  let airline#extensions#coc#stl_format_warn = '%W{[%w(#%fw)]}'
'''

[[plugins]]
repo = 'neoclide/coc-json'
build = 'yarn install --frozen-lockfile'
on_source = ['coc.nvim']

[[plugins]]
repo = 'coc-extensions/coc-powershell'
build = 'yarn install --frozen-lockfile'
on_source = ['coc.nvim']

# ------
# unite
# ------
# [[plugins]]
# repo = 'Shougo/unite.vim'
# hook_add = '''
  # nnoremap [unite] <Nop>
  # nmap <Leader>u [unite]
  # let g:unite_enable_start_insert = 1
  # let g:unite_source_file_mru_limit = 50
  # let g:unite_source_file_mru_filename_format = ''
  # nnoremap [unite]f :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
  # nnoremap [unite]b :<C-u>Unite buffer<CR>
  # nnoremap [unite]r :<C-u>Unite -buffer-name=register register<CR>
  # nnoremap [unite]m :<C-u>Unite file_mru<CR>
  # nnoremap [unite]c :<C-u>Unite bookmark<CR>
  # nnoremap [unite]a :<C-u>UniteBookmarkAdd<CR>
  # autocmd FileType unite call s:unite_my_settings()
  # function! s:unite_my_settings()
    # nmap <buffer> <ESC> <Plug>(unite_exit)
    # nnoremap <buffer> <expr> <C-j> unite#do_action('split')
    # inoremap <buffer> <expr> <C-j> unite#do_action('split')
    # nnoremap <buffer> <expr> <C-l> unite#do_action('vsplit')
    # inoremap <buffer> <expr> <C-l> unite#do_action('vsplit')
    # nnoremap <buffer> <expr> <C-o> unite#do_action('open')
    # inoremap <buffer> <expr> <C-o> unite#do_action('open')
  # endfunction
# '''

# [[plugins]]
# repo = 'Shougo/neomru.vim'
# on_source = ['unite.vim']

# ---------
# Markdown
# ---------
[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'

[[plugins]]
repo = 'previm/previm'
on_ft = 'markdown'
hook_source = '''
  let g:previm_disable_default_css = 1
  let g:previm_custom_css_path = '~/vimfiles/stylesheet/markdown.css'
  nnoremap <F5> :PrevimOpen<CR>
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_source = '''
  let g:vim_markdown_conceal=0
'''

# -----------
# powershell
# -----------
[[plugins]]
repo = 'PProvost/vim-ps1'
on_ft = 'ps1'

# -----------
# toml
# -----------
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# -----------
# csv
# -----------
[[plugins]]
repo = 'junegunn/vim-easy-align'
on_ft = ['csv']
hook_source = '''
  xmap ga <Plug>(EasyAlign)
  nmap ga <Plug>(EasyAlign)
'''
