[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'PProvost/vim-ps1'
